name: Preview example site
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
concurrency: preview-${{ github.ref }}
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    # Only run if this PR is not from a fork
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: test
